name: flutter_webview_js_channel
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.1.5
  freezed: ^3.2.0
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  os_info_plugin: ^0.0.1
  tosspayments_widget_sdk_flutter: ^2.1.1
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.10.0
  build_runner: ^2.6.0

flutter:
  uses-material-design: true
